import { materiais } from "@/types/types";

export const Array_materiais: materiais[] = [
  {
    id: 1,
    name: "Plastico Misto",
    group: "Plasticos",
    price: 1.0,
    priceSell: 1.5,
    status: true,
  },
  {
    id: 2,
    name: "Pet Mista",
    group: "Plasticos",
    price: 3.0,
    priceSell: 4.0,
    status: true,
  },
  {
    id: 3,
    name: "Pet Separada",
    group: "Plasticos",
    price: 4.5,
    priceSell: 5.6,
    status: true,
  },
  {
    id: 4,
    name: "Ferro",
    group: "Ferrosos",
    price: 1.0,
    priceSell: 1.5,
    status: true,
  },
  {
    id: 5,
    name: "Metal",
    group: "Metais Nobres",
    price: 23.0,
    priceSell: 31,
    status: true,
  },
  {
    id: 6,
    name: "Cobre 1",
    group: "Metais Nobres",
    price: 40.0,
    priceSell: 50,
    status: true,
  },
  {
    id: 7,
    name: "Cobre 2",
    group: "Metais Nobres",
    price: 39.55,
    priceSell: 48,
    status: true,
  },
];
